# NOTE: Please read ./README.md before using this
#
services:
  react:
    build:
      context: ../
      target: dev
    command: sh -c 'pnpm install --frozen-lockfile && pnpm start --host'
    environment:
      APP_TITLE: ${APP_TITLE:-CMS}
      APP_GRAPHQL_ENDPOINT: ${APP_GRAPHQL_ENDPOINT:-http://localhost:8001/graphql/}
      APP_GRAPHQL_CODEGEN_ENDPOINT: ${APP_GRAPHQL_CODEGEN_ENDPOINT:-./backend/schema.graphql}
    volumes:
      - ../:/code
    ports:
      - '3000:3000'
    depends_on:
      - web
